# Generated by Django 4.2.24 on 2025-09-27 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la estación', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único de la estación (ej: RIO_001)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener solo letras mayúsculas, números y guiones bajos.', regex='^[A-Z0-9_]+$')], verbose_name='Código')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitud de la estación', max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitud de la estación', max_digits=11, verbose_name='Longitud')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'db_table': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
            ],
            options={
                'verbose_name': 'Asignación de Estación',
                'verbose_name_plural': 'Asignaciones de Estaciones',
                'db_table': 'station_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
