# Generated by Django 4.2.24 on 2025-09-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='stationassignment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='stationassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='station',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_stations', through='stations.StationAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Asignados'),
        ),
        migrations.AlterUniqueTogether(
            name='stationassignment',
            unique_together={('user', 'station')},
        ),
    ]
