# Generated by Django 4.2.24 on 2025-09-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sensor_type', models.CharField(choices=[('water_level', 'Nivel de Agua'), ('flow_rate', 'Caudal'), ('temperature', 'Temperatura'), ('ph', 'pH')], max_length=20, verbose_name='Tipo de Sensor')),
                ('unit', models.CharField(help_text='cm, l/s, °C, etc.', max_length=20, verbose_name='Unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('calibration_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Factor de Calibración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensors',
                'ordering': ['station', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
