# Generated by Django 4.2.24 on 2025-09-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='stations.station', verbose_name='Estación'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('station', 'sensor_type')},
        ),
    ]
