# Generated by Django 5.0.1 on 2025-12-12 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Usuario inició sesión'), ('LOGOUT', 'Usuario cerró sesión'), ('CREATE', 'Creación de registro'), ('UPDATE', 'Actualización de registro'), ('DELETE', 'Eliminación de registro'), ('VIEW', 'Visualización de registro'), ('EXPORT', 'Exportación de datos'), ('IMPORT', 'Importación de datos'), ('ALERT', 'Alerta generada'), ('ALERT_RESOLVED', 'Alerta resuelta'), ('CONFIG_CHANGE', 'Cambio de configuración'), ('SYSTEM', 'Evento del sistema')], db_index=True, max_length=20, verbose_name='Tipo de acción')),
                ('entity_type', models.CharField(choices=[('USER', 'Usuario'), ('STATION', 'Estación'), ('SENSOR', 'Sensor'), ('MEASUREMENT', 'Medición'), ('ALERT', 'Alerta'), ('THRESHOLD', 'Umbral'), ('REPORT', 'Reporte'), ('CONFIGURATION', 'Configuración'), ('SYSTEM', 'Sistema')], db_index=True, max_length=20, verbose_name='Tipo de entidad')),
                ('entity_id', models.IntegerField(blank=True, help_text='ID del registro afectado', null=True, verbose_name='ID de entidad')),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', max_length=10, verbose_name='Severidad')),
                ('description', models.TextField(help_text='Descripción de la actividad', verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action_type'], name='users_activ_timesta_639a2b_idx'), models.Index(fields=['user', '-timestamp'], name='users_activ_user_id_8a5363_idx'), models.Index(fields=['entity_type', 'entity_id'], name='users_activ_entity__ea52e3_idx'), models.Index(fields=['severity', '-timestamp'], name='users_activ_severit_cab0cb_idx')],
            },
        ),
    ]
